// import list from "../asset/images/list.png"

// export  {list}  
const Images = {list:require("../asset/images/list.png"),
                exclusive:require("../asset/images/exclusive.png"),
                ul:require("../asset/images/ul.png"),
                logo:require("../asset/images/logo.png"),
                user:require("../asset/images/user.png"),
                navbar:require("../asset/images/navbar.png"),
                vector:require("../asset/images/vector.png"),
                cart1:require("../asset/images/cart1.png"),
                search:require("../asset/images/search.png"),
                symbol:require("../asset/images/symbol.png"),
                iphone:require("../asset/images/iphone.png"),
                shopnow:require("../asset/images/shopnow.png"),
                rectangle:require("../asset/images/rectangle.png"),
                doteed:require("../asset/images/doteed.png"),
                arrow_left:require("../asset/images/arrow_left.png"),
                arrow_right:require("../asset/images/arrow_right.png"),
                FillEye:require("../asset/images/FillEye.png"),
                Gamepad:require("../asset/images/Gamepad.png"),
                Ellipse:require("../asset/images/Ellipse.png"),
                Keyboard:require("../asset/images/keybord.png"),
                leptop:require("../asset/images/leptop.png"),
                chair:require("../asset/images/Chair.png"),
                phone:require("../asset/images/phone.png"),
                watch:require("../asset/images/watch.png"),
                camera:require("../asset/images/camera.png"),
                gameing:require("../asset/images/gameing.png"),
                computer:require("../asset/images/computers.png"),
                headphones:require("../asset/images/headphones.png"),
                coat:require("../asset/images/coat.png"),
                cpu:require("../asset/images/cpu.png"),
                guccibag:require("../asset/images/guccibag.png"),
                booksel:require("../asset//images/booksel.png"),
                food:require("../asset/images/food.png"),
                canon:require("../asset/images/canon.png"),
                gameingleptop:require("../asset/images/gameingleptop.png"),
                facewose:require("../asset/images/facewose.png"),
                car:require("../asset/images/car.png"),
                soccer:require("../asset/images/soccer.png"),
                shooter:require("../asset/images/shooter.png"),
                jacket:require("../asset/images/jacket.png"),
                dropdown:require("../asset/images/dropdown.png"),
                jbl:require("../asset/images/jbl.png"),
                full:require("../asset/images/full.png"),
                station:require("../asset/images/station.png"),
                women:require("../asset/images/women.png"),
                speakers:require("../asset/images/speakers.png"),
                gucci:require("../asset/images/gucci.png"),
                fast:require("../asset/images/fast.png"),
                service:require("../asset/images/service.png"),
                money:require("../asset/images/money.png"),
                iapple:require("../asset/images/iapple.png"),
                google:require("../asset/images/google.png"),
                quercode:require("../asset/images/quercode.png"),
                friend:require('../asset/images/friend.png'),
                singup:require("../asset/images/singup.png"),
                havic:require("../asset/images/havic.png"),
                dobblehavic:require("../asset/images/dobblehavic.png"),
                firstside:require("../asset/images//firstside.png"),
                leftside:require("../asset/images/leftside.png"),
                rightside:require("../asset/images/rightside.png"),
                delete:require("../asset/images/delete.png"),
                bkash:require('../asset/images/bkash.png'),
                visa:require('../asset/images/visa.png'),
                mastrcards:require('../asset/images/mastrcards.png'),
                banklogo:require('../asset/images/banklogo.png'),
                demo:require('../asset/images/demo.png'),
                ourstory:require('../asset/images/ourstory.png'),
                willsmith:require('../asset/images/willsmith.png'),
                emmawatson:require('../asset/images/emmawatson.png'),
                tomcruise:require('../asset/images/tomcruise.png')


                

}

export default  Images
 