// import list from "../asset/images/list.png"

// export  {list}  
const Images = {list:require("../asset/images/list.png"),
                exclusive:require("../asset/images/exclusive.png"),
                ul:require("../asset/images/ul.png"),
                logo:require("../asset/images/logo.png"),
                user:require("../asset/images/user.png"),
                navbar:require("../asset/images/navbar.png"),
                vector:require("../asset/images/vector.png"),
                cart1:require("../asset/images/cart1.png"),
                search:require("../asset/images/search.png"),
                symbol:require("../asset/images/symbol.png"),
                iphone:require("../asset/images/iphone.png"),
                shopboy:require("../asset/images/shopboy.png"),
                rectangle:require("../asset/images/rectangle.png"),
                doted:require("../asset/images/doted.png"),
                arrow_left:require("../asset/images/arrow_left.png"),
                arrow_right:require("../asset/images/arrow_right.png"),
                FillEye:require("../asset/images/FillEye.png"),
                Gamepad:require("../asset/images/Gamepad.png"),
                Ellipse:require("../asset/images/Ellipse.png"),
                Keyword:require("../asset/images/keyword.png"),
                laptop:require("../asset/images/laptop.png"),
                chair:require("../asset/images/Chair.png"),
                phone:require("../asset/images/phone.png"),
                watch:require("../asset/images/watch.png"),
                camera:require("../asset/images/camera.png"),
                gaming:require("../asset/images/gaming.png"),
                computer:require("../asset/images/computers.png"),
                headphones:require("../asset/images/headphones.png"),
                coat:require("../asset/images/coat.png"),
                cpu:require("../asset/images/cpu.png"),
                bag:require("../asset/images/bag.png"),
                books:require("../asset//images/books.png"),
                food:require("../asset/images/food.png"),
                canon:require("../asset/images/canon.png"),
                gameingleptop:require("../asset/images/gameingleptop.png"),
                faces:require("../asset/images/faces.png"),
                car:require("../asset/images/car.png"),
                soccer:require("../asset/images/soccer.png"),
                shooter:require("../asset/images/shooter.png"),
                jacket:require("../asset/images/jacket.png"),
                dropdown:require("../asset/images/dropdown.png"),
                jbl:require("../asset/images/jbl.png"),
                full:require("../asset/images/full.png"),
                station:require("../asset/images/station.png"),
                women:require("../asset/images/women.png"),
                speakers:require("../asset/images/speakers.png"),
                gucci:require("../asset/images/gucci.png"),
                fast:require("../asset/images/fast.png"),
                service:require("../asset/images/service.png"),
                money:require("../asset/images/money.png"),
                apple:require("../asset/images/apple.png"),
                google:require("../asset/images/google.png"),
                quenched:require("../asset/images/quenched.png"),
                friend:require('../asset/images/friend.png'),
                signup:require("../asset/images/signup.png"),
                havoc:require("../asset/images/havoc.png"),
                dobblehavic:require("../asset/images/dobblehavic.png"),
                fireside:require("../asset/images//fireside.png"),
                leftism:require("../asset/images/leftism.png"),
                rightsize:require("../asset/images/rightsize.png"),
                delete:require("../asset/images/delete.png"),
                bash:require('../asset/images/bash.png'),
                visa:require('../asset/images/visa.png'),
                mastercard:require('../asset/images/mastercard.png'),
                backlog:require('../asset/images/backlog.png'),
                demo:require('../asset/images/demo.png'),
                oratory:require('../asset/images/oratory.png'),
                wellsite:require('../asset/images/wellsite.png'),
                emanation:require('../asset/images/emanation.png'),
                cruise:require('../asset/images/cruise.png')


                

}

export default  Images
 